### ISSUE TITLE
Implement TTL method

### ISSUE THREAD

**Issue by dimostenis** [MrThearMan/sqlite3-cache#1]
Hello,
I hope you will be happy to hear we are giving your sqlite3 cache spin in our IT company. Its pretty cool (best implementation we found actually).

However, we miss a redis-like method for getting a TTL ("exp" in your code).

Somth like:
1. `cache.ttl(key)` -> `60` (key expires in a minute)
2. `cache.ttl(key)` -> `-1` (key does not have expiry)
3. `cache.ttl(key)` -> `-2` (key does not exist, it expired probably)

It doesnt have to follow redis rules like I propose, its your lib. But you get my point.

Its basically for debug-logging purposes.

Thank you for your work.

**Comment by MrThearMan** [comment]
Hey, nice to hear you're finding it useful!

I've added the requested method with the rules as described. It's available in version [0.2.0](https://github.com/MrThearMan/sqlite3-cache/releases/tag/v0.2.0). Should be available from [PyPI](https://pypi.org/project/sqlite3-cache/) as well.

**Comment by dimostenis** [comment]
Cool. Thx a lot!
